---
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: xu-cheng/latex-action@v2
        with:
          root_file: proposal.tex
      - uses: actions/upload-artifact@v2
        with:
          path: proposal.pdf
