---
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: xu-cheng/latex-action@v2
        with:
          root_file: proposal.tex
          args: >
            -pdf -file-line-error -halt-on-error -interaction=nonstopmode
            -jobname=docs/%A
      - uses: JamesIves/github-pages-deploy-action@dev
        with:
          branch: gh-pages
          folder: docs
          single-commit: true
